# Generated by Django 5.2.5 on 2025-09-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_prenda_imagen_alter_carritodecompras_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
