# Generated by Django 5.2.5 on 2025-09-15 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0003_prenda_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritodecompras',
            name='cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to='configuraciones.cliente'),
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='configuraciones.carritodecompras')),
                ('prenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.prenda')),
            ],
        ),
    ]
