# Generated by Django 5.2.5 on 2025-11-29 21:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0004_alter_carritodecompras_cliente_itemcarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prenda',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prenda',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prenda',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='prenda',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='prenda',
            index=models.Index(fields=['slug'], name='configuraci_slug_796cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='prenda',
            index=models.Index(fields=['nombre'], name='configuraci_nombre_633761_idx'),
        ),
        migrations.AddIndex(
            model_name='prenda',
            index=models.Index(fields=['is_archived'], name='configuraci_is_arch_f70301_idx'),
        ),
    ]
