# Generated by Django 6.0.2 on 2026-02-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0005_prenda_archived_at_prenda_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
