# Generated by Django 5.2.11 on 2026-02-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0006_prenda_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='precio_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
