# Generated by Django 5.2.11 on 2026-02-28 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0007_prenda_precio_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='wompi_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TransaccionWompiPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(db_index=True, max_length=50, unique=True)),
                ('monto_centavos', models.PositiveIntegerField()),
                ('procesado', models.BooleanField(default=False)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_wompi_pendientes', to='configuraciones.cliente')),
            ],
        ),
    ]
