# Generated by Django 5.2.11 on 2026-03-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0008_wompi_webhook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='wompi_transaction_id',
        ),
        migrations.RemoveField(
            model_name='prenda',
            name='precio_descuento',
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='TransaccionWompiPendiente',
        ),
    ]
