# Generated by Django 5.2.5 on 2026-03-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0009_remove_pago_wompi_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='precio_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
