# Generated by Django 5.2.5 on 2026-03-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0010_prenda_precio_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
