# Generated by Django 5.2.5 on 2026-03-12 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0011_prenda_barcode_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuponDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('porcentaje', models.PositiveIntegerField(help_text='0-100')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_expiracion', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_envio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='guia_rastreo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='transportadora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='venta',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.cupondescuento'),
        ),
        migrations.CreateModel(
            name='VariacionPrenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('talla', models.CharField(help_text='Ej: S, M, L, XL', max_length=10)),
                ('color', models.CharField(blank=True, help_text='Ej: Rojo, Azul, Negro', max_length=50, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/variaciones/')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variaciones', to='configuraciones.prenda')),
            ],
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='variacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.variacionprenda'),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='variacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.variacionprenda'),
        ),
    ]
