# Generated by Django 5.2.12 on 2026-03-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0012_cupondescuento_pedido_ciudad_pedido_costo_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='es_destacado',
            field=models.BooleanField(default=False),
        ),
    ]
