# Generated by Django 5.2.12 on 2026-03-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0013_prenda_es_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='es_oferta',
            field=models.BooleanField(default=False),
        ),
    ]
